services:
  - type: web
    name: mongodb-transfer-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_bot_token_here
      - key: ADMIN_CHAT_ID
        value: your_admin_chat_id
      - key: PORT
        value: 8080
      - key: RENDER_EXTERNAL_URL
        generateValue: true
